name: CI devops 2023

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: 'GITHUB_ACTOR'
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test with Maven
        run: mvn clean install
        #TODO: Add any additional Maven build commands or options
